from spike import Motor
from spike import MotorPair

Movement_pair = MotorPair('F', 'B')
Motor_F = Motor('F')
Motor_B = Motor('B')
Motor_D = Motor('D')

Movement_pair.move(2, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(1.25, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(1.8, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(0.7, 'rotations')
Motor_F.run_for_rotations(0.8)
Motor_D.run_for_rotations(0.2)
Movement_pair.move(0.55, 'rotations')
Motor_D.run_for_rotations(-0.2)
Motor_F.run_for_rotations(0.3)
Motor_D.run_for_rotations(0.2)
Motor_F.run_for_rotations(0.25)
Movement_pair.move(0.8, 'rotations')
Motor_F.run_for_rotations(0.3)
Movement_pair.move(0.5, 'rotations')
Motor_F.run_for_rotations(-0.45)
Movement_pair.move(2, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(1.3, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(1.3, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(2, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(1.3, 'rotations')
Motor_F.run_for_rotations(0.8)
Movement_pair.move(2, 'rotations')
